name: Auto-merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number to merge'
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'Prince527Github'
    steps:
      - name: Auto-merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.PR_NUMBER 
              ? parseInt(process.env.PR_NUMBER) 
              : context.payload.pull_request?.number;

            if (!prNumber) {
              console.log("No PR number found.");
              return;
            }

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            if (pr.state === "open" && !pr.draft) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: "squash"
              });
              console.log(`PR #${prNumber} merged.`);
            } else {
              console.log(`PR #${prNumber} is not ready to be merged.`);
            }
        env:
          PR_NUMBER: ${{ inputs.pr_number }}