name: Update Tap

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Tap Repo
        run: brew tap ${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY)

      - name: Get packages
        run: |
          FORMULAE=$(find Formula -name '*.rb' -exec basename {} .rb \; | sort | paste -sd' ' -)
          CASKS=$(find Casks -name '*.rb' -exec basename {} .rb \; | sort | paste -sd' ' -)

          echo "FORMULAE=$FORMULAE" >> $GITHUB_ENV
          echo "CASKS=$CASKS" >> $GITHUB_ENV

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.TOKEN }}
          formulae: ${{ env.FORMULAE }}
          casks: ${{ env.CASKS }}
          fork: false
