name: Update Tap

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Tap Repo
        run: brew tap ${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY) .

      - name: Get packages
        run: |
          FORMULAE=$(find Formula -name '*.rb' -exec basename {} .rb \; | sort)
          CASKS=$(find Casks -name '*.rb' -exec basename {} .rb \; | sort)

          echo "FORMULAE<<EOF" >> $GITHUB_ENV
          echo "$FORMULAE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "CASKS<<EOF" >> $GITHUB_ENV
          echo "$CASKS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formulae: ${{ env.FORMULAE }}
          casks: ${{ env.CASKS }}
          fork: false
